### PR TITLE
Review and Minor Changes on Physics

### PR DESCRIPTION
**Pull request by KarlZeilhofer**
Hi, 
we once had an ongoing discussion about the physics of the game, see #37. Thanks again for your great game!

Here is the PR for all my "contributions", which are more of comments, renamings and todos, than actually fixing something. 

Perhaps you are willing to accept my stuff, so the issues can be fixed more easily in the future. 

Greets, Karl
PS: I love the nature of open source: I've given the AI only 20% of power, and so my 4 years old son can learn playing without frustration :) That's of course not included in this PR.

### CODE REVIEW

**Comment by juzzlin** [comment]
Cool, I'll take a look at these changes :)

**Comment by KarlZeilhofer** [comment]
Hi, 
I found now a major scaling bug in the physics object. The location was used from the MCObject, which is in scene coordinates. I fixed that, but the current commit (7701c875131) has still a problem regarding scaling. Cars behave very heavy! But at least the speedometer now makes sense without any fuzzy factor. 
Greets, Karl

**Comment by juzzlin** [comment]
Well, that'll explain that, then :) Maybe the calculations and settings regarding moment of inertia would also need some fixing..?

**Comment by juzzlin** [comment]
Could you by any means rename, fixup or squash those "WIP" commits?

**Comment by juzzlin** [comment]
I have now investigated some of your findings (thanks a lot for the observations!). I now think that the best solution to make things better would be to first fix the stupid meters vs scene units problem :) Unfortunately that's not trivial to do. I should have used meters only right from the beginning.

**Comment by KarlZeilhofer** [comment]
I'm currently trying to fix exactly this. I think, scene units will stay scene units, right? The question is, what objects should by default use metric units, and which should use scene units. 

For the tires of the car, for example, I've introduced temporarily a parameter for the getters, which defines the wanted unit (metric vs. scene). This reveals some errors, where units were mixed. 

Or do you suggest, to scale the scene units also?

**Comment by juzzlin** [comment]
I had similar ideas, but everything seemed to be pain. 

I would probably do it so that the scene and surface data is converted to meters when it's being loaded. So, everything in MCObject and MCPhysicsComponent etc would be in meters. Then convert back to scene coordinates only when rendering. This could still be a lot of work to fix all side-effects, but would be clear enough.

**Comment by KarlZeilhofer** [comment]
Your suggestion sounds good. I'll try to do it step by step, and running the game in every little step, and check for errors.

**Comment by KarlZeilhofer** [comment]
Your suggestion sounds good. I'll try to do it step by step, and running the game in every little step, and check for errors. 

My current state of development is playable again, with only one workaround, as far as I know, regarding the steering force: 87bf94b15ebef5c418cf539b00365aa8b2b0f8d5

**Pull request closed without merging**
