### PR TITLE
OpenGL disabled build fixes proposal.

### PR DESCRIPTION
**Pull request by devnexen**
SQL requests parameters binding accept qvariant and children only.

### CODE REVIEW

**Comment by juzzlin** [comment]
Looks ok, but what's the story behind this? How is OpenGL related?

**Comment by devnexen** [comment]
No real idea but this is when I disabled the gl functions the build issues occured.

**Comment by juzzlin** [comment]
> No real idea but this is when I disabled the gl functions the build issues occured.

Ok, I was able to reproduce that. Let me check..

**Comment by juzzlin** [comment]
To me it seemed like `#include <QVariant>` was missing from database.cpp and it probably was implicitly pulled by QOpenGLFunctions. I fixed this in 8af0bfe0c5598f0a7aeda256e5de97b192362cde. Please check if this fixes the issue also for you :)

**Comment by devnexen** [comment]
it does, thx

**Pull request closed without merging**
